### ISSUE TITLE
05 - Rewards Pages (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/sweet-caramel#1006]

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/1006?planning-poker) with ZenHub @Ajiva-D @Amirjab21 @arne-z @ecmendenhall @K-G-J @RedVeil

**Comment by Ajiva-D** [comment]
Pr: https://github.com/popcorndao/sweet-caramel/pull/1094
deploy link: https://sweet-caramel-git-new-rewards-page-popcorn-dao.vercel.app/ethereum/rewards

**Comment by FanFanDAO** [comment]
@Ajiva-D @RedVeil @anthonymartin 
1) Use this SVG for the empty states under vesting records:
![no records_mobile.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8ba37a37-a6bf-4b01-bac9-c272b122d12a)
![no records.svg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/09b51177-2f17-476b-ba11-c408ec519e38)
![Screen Shot 2022-08-12 at 8.48.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ed12b37b-34eb-4c96-8c17-291d8a363343)
2) Remove magnifying animation since we didn't use it elsewhere. For example, the .finance landing page.
3) Padding error:
![Screen Shot 2022-08-12 at 8.51.52 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a7ef6d4e-72c2-42b4-af95-8838b878bd09)
![Screen Shot 2022-08-12 at 8.51.46 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f11c1ba0-f1c5-4cf9-8353-772003d7041c)

**Comment by Ajiva-D** [comment]
@FanFanDAO all comments have been addressed

**Comment by FanFanDAO** [comment]
@Ajiva-D, somehow we still show this popover. 
![Screen Shot 2022-08-15 at 7.33.41 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/003ad2e1-e238-4209-a555-2947c030ccc7)
Use this SVG above for mobile:
![Screen Shot 2022-08-15 at 7.35.30 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/75f6a7fa-b950-4be0-b61f-c76d060230d9)

**Comment by Ajiva-D** [comment]
@FanFanDAO that can't be used as an svg, it will be done with html and css. 
Please how did you get the popover? cause the empty vesting records has been replaced.

**Comment by FanFanDAO** [comment]
@Ajiva-D It just shows up when I connected my Metamask wallet. I didn't do anything special, actually. I am on chrome.

**Comment by Ajiva-D** [comment]
@FanFanDAO, the popovers that have been done are in a different branch from the one for this rewards page. So you are seeing the old popovers, when everything is merged into the same branch, this popover won't be like this, but will be the updated one.

**Comment by FanFanDAO** [comment]
@Amirjab21 Got it! Thanks for the info. Feedback:
![Screen-Shot-2022-08-16-at-3.39.28-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/59fe8141-9243-42cb-b6bf-375f63451575)
![Screen-Shot-2022-08-16-at-3.39.48-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a726b2f3-b791-41e8-b9f2-811b0b753927)

**Comment by FanFanDAO** [comment]
No change made! @Ajiva-D

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
https://www.loom.com/share/d55d23bea0cf492d9b5dcac9afc1b7ac
![Screen Shot 2022-08-18 at 12.32.36 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ef5ea90c-3eeb-42f1-8989-9116038f426c)
![Screen-Shot-2022-08-18-at-12.32.08-PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ebe7a273-ef04-4bb5-b5bd-8c2e303ed37e)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback: Footer always adheres to the bottom browser in relative spacing.
![Screen Shot 2022-08-18 at 1.27.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c1a61c56-7248-4f38-b494-c2eb5ee321ed)
reference: will there be a conflict with other pages if we make this element auto-fill?
![Screen Shot 2022-08-18 at 1.32.58 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bc679956-c1fa-4f30-a411-2f0a14556c1e)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback:
![Screen Shot 2022-08-18 at 1.26.34 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c5112cdf-6b20-4745-96ef-b9a327232e94)

**Comment by FanFanDAO** [comment]
@Ajiva-D Feedback: Please always check 1100px, 1440px 2200px and 375px
Below is found at 1100px
![Screen Shot 2022-08-18 at 5.36.31 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f691fcf1-6f80-4bf4-84c4-aff720e84eeb)

**Comment by FanFanDAO** [comment]
@Ajiva-D feedback: on mobile
![Screen Shot 2022-08-18 at 5.36.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9e0bf44c-c1ff-4f59-b4e2-e3b2331af8bc)

**Comment by Ajiva-D** [comment]
@FanFanDAO please what exactly is the feedback on mobile? If it's the overflow, I think that was just your browser inspector misbehaving.

**Comment by FanFanDAO** [comment]
@Ajiva-D, we synced this afternoon so all good.
